@startuml
sprite $Compute_Kubernetes_Cluster [
                                                                
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFF00000FFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFF000FFF00FFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFF00FFFFFF000FFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFF000FFFFFFFFF000FFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFF000FFFFFFFFFFFFF000FFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFF000FFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFF000FFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFF0FFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFF0FFFFFFFFF00000FFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFF0FFFFFFF000FFF000FFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFF0FFFFFF00FFFFFFF00FFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFF0FFFFFF0FFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFF0FFFFFF0FFFFFFFFF0FFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFF0FFFFFF0FFFFFFFFF0FFFFF00FFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFF0FFFFFF0FFFFFFFFF0FFFFF00FFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFF0FFFFFF0FFFFFFFFF0FFFFF00FFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFF0FFFFFF00FFFFFFF00FFFFF00FFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFF0FFFFFFF00FFFF000FFFFFF00FFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFF0FFFFFFFF000F000FFFFFFF00FFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFF0FFFFFFFFFF000FFFFFFFFF00FFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFF000FFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFF000FFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFF000FFFFFFF000FFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFF00FFFF000FFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFF000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFF000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
]

@enduml
