@startuml
sprite $Applications_Mobile_Application[64x64/16] {
                          FFFFFFFFFFFF                          
                      FFFFFFFFFFFFFFFFFFFF                      
                    FFFFFFFFFFFFFFFFFFFFFFFF                    
                 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF                 
                FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF                
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF              
             FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF             
           FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF           
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF          
         FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF         
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF        
       FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF       
       FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF       
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF      
     FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF     
     FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF     
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF    
   FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF   
   FFFFFFFFFFFFFFFFFFFF00000000000000FFFFFFFFFFFFFFFFFFFFFFFF   
   FFFFFFFFFFFFFFFFFFF000000000000000FFFFFFFFFFFFFFFFFFFFFFFF   
  FFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF  
  FFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF  
 FFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFF00FFFFFFFFF0000FF0000FFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFF00FFFFFFFFF0000FF0000FFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFF00FFFFFFFFF0000FF0000FFFFFFFFFFFFFFFFFFFF 
FFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFF0000FF0000FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFF0000FF0000FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFF0000FF0000FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFF0000FF0000FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFF0000FF0000FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFFFFF
 FFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFF00FFFFFF0FFFFFF00FFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFF00FFFFF000FFFFF00FFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFF00FFFFFF0FFFFFF00FFFFFFFFFFFFFFFFFFFFFFFF 
  FFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFFF  
  FFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFFF  
   FFFFFFFFFFFFFFFFFFF00000000000000000FFFFFFFFFFFFFFFFFFFFFF   
   FFFFFFFFFFFFFFFFFFFF000000000000000FFFFFFFFFFFFFFFFFFFFFFF   
   FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF   
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF    
     FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF     
     FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF     
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF      
       FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF       
       FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF       
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF        
         FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF         
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF          
           FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF           
             FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF             
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF              
                FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF                
                 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF                 
                    FFFFFFFFFFFFFFFFFFFFFFFF                    
                      FFFFFFFFFFFFFFFFFFFF                      
                          FFFFFFFFFFFF                          
}

@enduml
