@startuml
sprite $Applications_Virtual_Application [
                          FFFFFFFFFFFF                          
                      FFFFFFFFFFFFFFFFFFFF                      
                    FFFFFFFFFFFFFFFFFFFFFFFF                    
                 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF                 
                FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF                
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF              
             FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF             
           FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF           
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF          
         FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF         
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF        
       FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF       
       FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF       
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF      
     FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF     
     FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF     
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF    
   FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF   
   FFFFFFFFFFFFFFFFFFFFFFFFFF000000FFFFFFFFFFFFFFFFFFFFFFFFFF   
   FFFFFFFFFFFFFFFFFFFFFFFF0000000000FFFFFFFFFFFFFFFFFFFFFFFF   
  FFFFFFFFFFFFFFFFFFFFFFFF000FFFFFF000FFFFFFFFFFFFFFFFFFFFFFFF  
  FFFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFFF  
 FFFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFF 
FFFFFFFFFFFFFFFFFFFFF000FFFFFFFFFFFFFFFF000FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFF00000FFFFFFFFFFFFFFFF00000FFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFF000FFFFFFFFFFFFFFFFFFFFFF000FFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF000FFFFFFFFFFFFFFFFFFFFFFFF000FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFF00FFFFFFFFF0000FF0000FFFFFFFFF00FFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF00FFFFFFFF0000FF0000FFFFFFFF00FFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFF000FFFFFFF0000FF0000FFFFFFF000FFFFFFFFFFFFFFFFF
 FFFFFFFFFFFFFFFFF000FFFFFF0000FF0000FFFFFF000FFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFF00000FFFFFFFFFFFFFFFF00000FFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFF000FFFFFFFFFFFFFFFF000FFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFF0000FF0000FFFFFFFFFFFFFFFFFFFFFFFFFF 
  FFFFFFFFFFFFFFFFFFFFFFFFF0000FF0000FFFFFFFFFFFFFFFFFFFFFFFFF  
  FFFFFFFFFFFFFFFFFFFFFFFFF0000FF0000FFFFFFFFFFFFFFFFFFFFFFFFF  
   FFFFFFFFFFFFFFFFFFFFFFFF0000FF0000FFFFFFFFFFFFFFFFFFFFFFFF   
   FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF   
   FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF   
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF    
     FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF     
     FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF     
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF      
       FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF       
       FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF       
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF        
         FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF         
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF          
           FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF           
             FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF             
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF              
                FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF                
                 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF                 
                    FFFFFFFFFFFFFFFFFFFFFFFF                    
                      FFFFFFFFFFFFFFFFFFFF                      
                          FFFFFFFFFFFF                          
]

@enduml
