@startuml
sprite $AI_IBM__watsonx_governance_[64x64/16] {
                                                                
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFF0000000FFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFF0000000000000FFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFF0000FFFFFF000000FFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFF00000FFFFFFFFF0000000FFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFF0000FFFFFFFFFF00000000FFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFF000FFFFFFFFFFF00F000000FFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFF00FF00000FFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00FFF000000FFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFF0FFFFFFFF0FFF000FFFF00F0000FFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFF00FFFFFFF0FFF0FFFFFF0FF0000FFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFF00FF0000FFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFF00FF00F00FFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFF00FFF00F00FFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFF000FFF00F00FFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFF0000FFFF00F00FFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFF00FFFFFFFF0FFF0000FFFFFF0FF00FFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFF00FFFFFFFF0FFFFFFFFFFFF00FF00FFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFF00FFF00FFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFF00FFF0FFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFF00FFF00FFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFF000FFFF00FFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFF00000FFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFF00FFFFFF0FFF00000FFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFF000FFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFF00000FFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFF000FFFFFFFFFF0000FFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFF000000FFF00000FFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFF000000000FFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 
}

@enduml
