@startuml
sprite $Actors_Group [
                          FFFFFFFFFFFF                          
                      FFFFFFFFFFFFFFFFFFFF                      
                    FFFFFFFFFFFFFFFFFFFFFFFF                    
                 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF                 
                FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF                
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF              
             FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF             
           FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF           
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF          
         FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF         
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF        
       FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF       
       FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF       
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF      
     FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF     
     FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF     
    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF    
   FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF   
   FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF   
   FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF   
  FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF  
  FFFFFFFFFFFFFFFFFFFFFFF000000FFFFF000FFFFFFFFFFFFFFFFFFFFFFF  
 FFFFFFFFFFFFFFFFFFFFFF0000000000FFF00000FFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFFF00FFFFFF00FFFFFF00FFFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFFF00FFFFFFFF00FFFFFF00FFFFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFFF00FFFFFFFFFF00FFFFFF00FFFFFFFFFFFFFFFFFFFF 
FFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFF00FFFFFF00FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFF00FFFFFF00FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFF00FFFFFF00FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFF00FFFFFF00FFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF00FFFFFFFF00FFFFFF00FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF000FFFFFF000FFFFF000FFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFF0000FF0000FFFF0000FFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFF00000000FFFF0000FFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFF000000000000FFFFF000FFFFFFFFFFFFFFFFFFFFFF
 FFFFFFFFFFFFFFFFFFF0000000000000000FFF00000FFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFF00FFFFFF00FFFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFF00FFFFFF00FFFFFFFFFFFFFFFFFF 
 FFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFF00FFFFFF00FFFFFFFFFFFFFFFFF 
  FFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFF00FFFFFF00FFFFFFFFFFFFFFFF  
  FFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFF00FFFFFF00FFFFFFFFFFFFFFFF  
   FFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFF00FFFFFF00FFFFFFFFFFFFFFF   
   FFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFF00FFFFFF00FFFFFFFFFFFFFFF   
   FFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFF00FFFFFF00FFFFFFFFFFFFFFF   
    FFFFFFFFFFFFFF00FFFFFFFFFFFFFFFF00FFFFFF00FFFFFFFFFFFFFF    
     FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF     
     FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF     
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF      
       FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF       
       FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF       
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF        
         FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF         
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF          
           FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF           
             FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF             
              FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF              
                FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF                
                 FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF                 
                    FFFFFFFFFFFFFFFFFFFFFFFF                    
                      FFFFFFFFFFFFFFFFFFFF                      
                          FFFFFFFFFFFF                          
]

@enduml
